// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGLfiH76n4nZGVw2CPAZgbXpANt2AeA0w',
    appId: '1:523185127294:web:86eb4b124d73c9ba34fd2f',
    messagingSenderId: '523185127294',
    projectId: 'homefinder-4de5e',
    authDomain: 'homefinder-4de5e.firebaseapp.com',
    storageBucket: 'homefinder-4de5e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCspw2DnZ17ZzF_xwzaKZo3wZIUl7jwlMY',
    appId: '1:523185127294:android:b7ce9a77f97abd8434fd2f',
    messagingSenderId: '523185127294',
    projectId: 'homefinder-4de5e',
    storageBucket: 'homefinder-4de5e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJvn3IMuISGNc9_1UBpsKGx4Y0nW2CqV0',
    appId: '1:523185127294:ios:f1ced2b78a1404be34fd2f',
    messagingSenderId: '523185127294',
    projectId: 'homefinder-4de5e',
    storageBucket: 'homefinder-4de5e.firebasestorage.app',
    iosBundleId: 'com.example.homefinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJvn3IMuISGNc9_1UBpsKGx4Y0nW2CqV0',
    appId: '1:523185127294:ios:f1ced2b78a1404be34fd2f',
    messagingSenderId: '523185127294',
    projectId: 'homefinder-4de5e',
    storageBucket: 'homefinder-4de5e.firebasestorage.app',
    iosBundleId: 'com.example.homefinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGLfiH76n4nZGVw2CPAZgbXpANt2AeA0w',
    appId: '1:523185127294:web:dd1a9170a05f866e34fd2f',
    messagingSenderId: '523185127294',
    projectId: 'homefinder-4de5e',
    authDomain: 'homefinder-4de5e.firebaseapp.com',
    storageBucket: 'homefinder-4de5e.firebasestorage.app',
  );
}
